version: 1
disable_existing_loggers: True
formatters:
    simpleFormater:
        format: '%(levelname)s: %(asctime)s: %(filename)s:%(lineno)d %(thread)d %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        formatter: simpleFormater
        level: DEBUG
        stream: ext://sys.stderr
    file:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: simpleFormater
        when: h
        interval: 1
        backupCount: 0
        filename: 'info.log'
loggers:
    clogger:
        level: DEBUG
        handlers: [console]
    flogger:
        level: WARNING
        handlers: [file]
root:
    level: INFO
    handlers: [console, file]
    propagate : True
